# Site settings
title: Amy Traylor
description: Computational artist, educator, researcher
url: "" # Set to your custom domain once configured
baseurl: "" # Set to "/repo-name" if not using custom domain

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
